<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ranjeet-K" ignored="0" name="Test" tests="4" failures="1" timestamp="2022-03-20T01:41:53 IST" time="40.132" errors="0">
  <testcase name="launchBooking" time="5.204" classname="com.Booking.BookingTest">
    <skipped/>
  </testcase> <!-- launchBooking -->
  <testcase name="searchStay" time="10.677" classname="com.Booking.BookingTest">
    <skipped/>
  </testcase> <!-- searchStay -->
  <testcase name="launchBooking" time="2.772" classname="com.Booking.BookingTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.Booking.BookingTest.launchBooking(BookingTest.java:35)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- launchBooking -->
  <testcase name="searchStay" time="7.243" classname="com.Booking.BookingTest"/>
</testsuite> <!-- Test -->
